# yaml-language-server: $schema=https://json.schemastore.org/dependabot-2.0.json

version: 2
updates:
    - package-ecosystem: "docker"
      directory: "/"
      schedule:
          interval: "daily"
    - package-ecosystem: github-actions
      open-pull-requests-limit: 10
      directory: "/"
      schedule:
          interval: weekly
          time: "04:00"
    - package-ecosystem: pip
      open-pull-requests-limit: 10
      directory: "/"
      schedule:
          interval: weekly
          time: "04:00"
