# yaml-language-server: $schema=https://json.schemastore.org/pre-commit-config.json

repos:
    - repo: https://github.com/pre-commit/pre-commit-hooks
      rev: 3e8a8703264a2f4a69428a0aa4dcb512790b2c8c # v6.0.0
      hooks:
          - id: check-yaml
          - id: check-toml
          - id: end-of-file-fixer
          - id: trailing-whitespace
            args: [--markdown-linebreak-ext=md]
          - id: mixed-line-ending
            args: ["--fix=lf"]
          - id: no-commit-to-branch
          - id: check-added-large-files
            args: ["--maxkb=500"]

    - repo: https://github.com/astral-sh/ruff-pre-commit
      rev: 22f0422809455ec89ffdcf5a00170ba816e42ddb # v0.15.16
      hooks:
          - id: ruff
            name: lint
            alias: lint
          - id: ruff
            name: lint-fix
            alias: lint-fix
            args: [--fix]
            stages: [manual]
          - id: ruff-format
            name: format
            alias: format

    - repo: https://github.com/igorshubovych/markdownlint-cli
      rev: e72a3ca1632f0b11a07d171449fe447a7ff6795e # v0.48.0
      hooks:
          - id: markdownlint
          - id: markdownlint
            name: markdownlint-fix
            alias: markdownlint-fix
            args: ["--fix"]
            stages: [manual]

    - repo: https://github.com/pre-commit/mirrors-mypy
      rev: d2823d321df3af8f878f7ee3414dc94d037145b9 # v2.1.0
      hooks:
          - id: mypy
            additional_dependencies: [pytest]

    - repo: https://github.com/python-poetry/poetry
      rev: 811a12dae0fe81f199e3f1b88b8b8be9eed543c2 # 2.4.1
      hooks:
          - id: poetry-check
            stages: [pre-push]
          - id: poetry-export
            name: poetry-export
            stages: [manual]
            files: (pyproject\.toml|poetry\.lock)
            args:
                - "--without-hashes"
                - "-f"
                - "requirements.txt"
                - "-o"
                - "requirements.txt"
          - id: poetry-export
            name: poetry-export-dev
            alias: poetry-export-dev
            stages: [manual]
            files: (pyproject\.toml|poetry\.lock)
            args:
                - "--with"
                - "dev,lint,test"
                - "--without-hashes"
                - "-f"
                - "requirements.txt"
                - "-o"
                - "dev-requirements.txt"

    - repo: https://github.com/asottile/pyupgrade
      rev: 75992aaa40730136014f34227e0135f63fc951b4 # v3.21.2
      hooks:
          - id: pyupgrade
            args:
                - --py310-plus
                - --keep-percent-format
                - --keep-mock
                - --keep-runtime-typing
                - --exit-zero-even-if-changed
            stages: [manual]

    - repo: https://github.com/adhtruong/mirrors-typos
      # https://github.com/crate-ci/typos/issues/390
      rev: fc278e51f1abd13f03ccb2c18fdf75923329819c # v1.47.2
      hooks:
          - id: typos
            exclude: "(_typos.toml|.gitignore)"

    - repo: https://github.com/abravalheri/validate-pyproject
      rev: 4b2e70d08cb2ccd26d1fba73588de41c7a5d50b7 # v0.25
      hooks:
          - id: validate-pyproject
            additional_dependencies:
                - "validate-pyproject[all]"
                - "validate-pyproject-schema-store"
