services:
    beets-filetote:
        container_name: beets-filetote
        build: .
        command: tail -F anything
        restart: unless-stopped
        volumes:
            - .:/src
            - ./example.config.yaml:/root/.config/beets/config.yaml
