from typing import Any

class ConfigView:
    def __getitem__(self, key: str) -> Any: ...
    def __setitem__(self, key: str, value: Any) -> Any: ...

class RootView(ConfigView):
    sources: list[Any]
    def __init__(self, sources: list[Any]): ...

class Configuration(RootView):
    def __init__(
        self,
        appname: str,
        modname: str | None = None,
        read: bool = True,
    ): ...

class LazyConfig(Configuration):
    def __init__(self, appname: str, modname: str | None = None): ...
    def add(self, value: dict[str, Any]) -> None: ...
    def clear(self) -> None: ...
