# yaml-language-server: $schema=https://json.schemastore.org/github-workflow.json

name: Markdown Lint

permissions:
    contents: read

on:
    push:
        paths: ["**.md", "**.markdown"]
    pull_request:
        paths: ["**.md", "**.markdown"]
        types: [opened, reopened]

jobs:
    markdownlint:
        name: Markdown Lint
        runs-on: ubuntu-24.04
        steps:
            - name: Checkout Code
              uses: actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10 # v6.0.3

            - name: Lint Markdown Files
              uses: DavidAnson/markdownlint-cli2-action@ded1f9488f68a970bc66ea5619e13e9b52e601cd # v23.2.0
              with:
                  config: .markdownlint.yaml
                  globs: |
                      **.md
                      **.markdown
                      !src/**
