# yaml-language-server: $schema=https://json.schemastore.org/github-workflow.json

name: Prek (Pre-commit) Updater

permissions:
    contents: write
    pull-requests: write

on:
    schedule:
        - cron: "0 4 * * 0"
    workflow_dispatch:

env:
    PYTHON_VERSION: 3.14

jobs:
    autoupdate-prek-hooks:
        runs-on: ubuntu-24.04
        steps:
            - uses: actions/checkout@v6

            - name: Set up Python
              uses: actions/setup-python@v6
              with:
                  python-version: ${{ env.PYTHON_VERSION }}
                  cache: pip

            - name: Install `prek`
              run: pip install prek

            - name: Run `prek auto-update`
              run: prek auto-update

            - name: Create Pull Request
              uses: peter-evans/create-pull-request@v8
              with:
                  token: ${{ secrets.GITHUB_TOKEN }}
                  branch: update/prek-autoupdate
                  title: Auto-update `prek` hooks
                  commit-message: Auto-update `prek` hooks
                  body: |
                      Update versions of tools in `prek` configs to latest version(s).
                  labels: dependencies
