# yaml-language-server: $schema=https://json.schemastore.org/github-workflow.json

name: Pre-commit Updater

permissions:
    contents: write
    pull-requests: write

on:
    schedule:
        - cron: "0 4 * * 0"
    workflow_dispatch:

env:
    PYTHON_VERSION: 3.13

jobs:
    autoupdate-precommit:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4

            - name: Set up Python
              uses: actions/setup-python@v5
              with:
                  python-version: ${{ env.PYTHON_VERSION }}
                  cache: pip

            - name: Install pre-commit
              run: pip install pre-commit

            - name: Run pre-commit autoupdate
              run: pre-commit autoupdate

            - name: Create Pull Request
              uses: peter-evans/create-pull-request@v7
              with:
                  token: ${{ secrets.GITHUB_TOKEN }}
                  branch: update/pre-commit-autoupdate
                  title: Auto-update pre-commit hooks
                  commit-message: Auto-update pre-commit hooks
                  body: |
                      Update versions of tools in pre-commit
                      configs to latest version
                  labels: dependencies
