# yaml-language-server: $schema=https://json.schemastore.org/github-workflow.json

name: Test beets Master

permissions:
    contents: read

on:
    push:
    pull_request:
        types: [opened, reopened]

    schedule:
        - cron: "0 0 * * 1" # Every Monday at midnight UTC
    workflow_dispatch:

jobs:
    test-beets-master:
        name: Test against beets@master
        runs-on: ubuntu-24.04

        env:
            TOXENV: beets-master

        steps:
            - uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0

            - name: Setup Python
              id: setup-python
              uses: actions/setup-python@a309ff8b426b58ec0e2a45f0f869d46889d02405 # v6.2.0
              with:
                  python-version-file: .python-version

            - name: Setup uv
              uses: astral-sh/setup-uv@11f9893b081a58869d3b5fccaea48c9e9e46f990 # v8.3.2
              with:
                  enable-cache: true
                  cache-dependency-glob: |
                      uv.lock
                      pyproject.toml

            - name: Run Tests
              # Failures are sometimes expected, so this ensures they don't send failure notifications.
              continue-on-error: true
              run: uvx tox -e "$TOXENV"
