# yaml-language-server: $schema=https://json.schemastore.org/github-workflow.json

name: Test beets Master

permissions:
    contents: read

on:
    push:
    pull_request:
        types: [opened, reopened]

    schedule:
        - cron: "0 0 * * 1" # Every Monday at midnight UTC
    workflow_dispatch:

jobs:
    test-beets-master:
        name: Test against beets@master
        runs-on: ubuntu-24.04

        env:
            TOXENV: beets-master

        steps:
            - uses: actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10 # v6.0.3

            - name: Setup Python
              id: setup-python
              uses: actions/setup-python@a309ff8b426b58ec0e2a45f0f869d46889d02405 # v6.2.0
              with:
                  python-version-file: .tool-versions

            - name: Setup uv
              uses: astral-sh/setup-uv@v6
              with:
                  enable-cache: true
                  cache-dependency-glob: |
                      uv.lock
                      pyproject.toml

            - name: Cache tox environments
              id: cache-tox
              uses: actions/cache@27d5ce7f107fe9357f9df03efb73ab90386fccae # v5.0.5
              with:
                  path: .tox
                  key: tox-${{ runner.os }}-py-${{ steps.setup-python.outputs.python-version }}-${{ env.TOXENV }}-${{ hashFiles('**/pyproject.toml', '**/uv.lock') }}
                  restore-keys: |
                      tox-${{ runner.os }}-py-${{ steps.setup-python.outputs.python-version }}-${{ env.TOXENV }}-

            - name: Run Tests
              # Failures are sometimes expected, so this ensures they don't send failure notifications.
              continue-on-error: true
              run: uvx tox -e "$TOXENV"
